<a href="https://colab.research.google.com/github/JosephHauser912/SL-Projects/blob/main/NP%20Arrays%20-%20Cyclist%20Trials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from array import *

In [3]:
new_cyclist_trials = np.array([[10,15,17,26,13,1],[12,11,21,24,14,23]])

In [4]:
print(new_cyclist_trials)

[[10 15 17 26 13  1]
 [12 11 21 24 14 23]]


In [5]:
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13,  1, 12, 11, 21, 24, 14, 23])

In [6]:
new_cyclist_trials.reshape(3,4 )

array([[10, 15, 17, 26],
       [13,  1, 12, 11],
       [21, 24, 14, 23]])

In [7]:
new_cyclist_trials.resize(2,6)

new_cyclist_trials


In [13]:
new_cyclist_trials.resize(1,12)
print(new_cyclist_trials)
new_cyclist_trials.resize(2,6)
print(new_cyclist_trials)

[[10 15 17 26 13  1 12 11 21 24 14 23]]
[[10 15 17 26 13  1]
 [12 11 21 24 14 23]]


In [17]:
np.hsplit(new_cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13,  1],
        [24, 14, 23]])]

In [18]:
new_cyclist_1 = np.array([10,15,17,26,13,19])

In [19]:
new_cyclist_2 = np.array([12,11,21,24,14,23])

In [21]:
np.hstack((new_cyclist_1,new_cyclist_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])