<a href="https://colab.research.google.com/github/JosephHauser912/SL-Projects/blob/main/SL_NP_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from array import *

In [ ]:
new_cyclist_trials = np.array([10,15,17,26,13,12,11,21,24,14,2])

In [ ]:
np.ones((2,3), dtype=float, order='C')

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty((4,2), order='c')

array([[2.70285370e-316, 0.00000000e+000],
       [1.46921998e+195, 6.01347002e-154],
       [6.47523147e+170, 1.27919412e-152],
       [7.69972395e+218, 1.27919412e-152]])

In [ ]:
np.zeros_like(new_cyclist_trials, order='k', shape=(3,2))

array([[0, 0],
       [0, 0],
       [0, 0]])

In [25]:
a=np.zeros((10,2))

In [26]:
b=a.T

In [27]:
c = b.view()

In [28]:
c.shape = (20)

AttributeError: ignored

In [29]:
a = np.arange(6).reshape((3,2))

In [30]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
np.reshape(a,(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
np.reshape(np.ravel(a), (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
np.reshape(a,(2,3), order="F")

array([[0, 4, 3],
       [2, 1, 5]])